# This will enable almost every single warning
allow-shorthand: false

ignore-patterns:
  - (^|/)\..+

pylint:
  disable:
    - fixme
    - bad-continuation
    - missing-final-newline
    - too-few-public-methods
    - too-many-ancestors
    - unsubscriptable-object # this was added due to list[int] support, remove in python 3.10
    - bad-whitespace
    - W0613  # allow Unused arguments
    - W0142  # allow Used * or ** magic
    - R0201  # disable no-self-use

  options:
    max-locals: 25
    max-returns: 6
    max-branches: 20
    max-statements: 60
    min-public-methods: 1
    max-public-methods: 24
    max-line-length: 120
    max-args: 10
    max-module-lines: 1200
    max-attributes: 8
    # Regular expressions used to match various names
    # (we allow longer names than default)
    argument-rgx: "[a-z_][a-z0-9_]{2,60}$"
    attr-rgx: "[a-z_][a-z0-9_]{2,60}$"
    function-rgx: "[a-z_][a-z0-9_]{2,60}$"
    method-rgx: "[a-z_][a-z0-9_]{2,60}$"
    variable-rgx: "[a-z_][a-z0-9_]{2,60}$"

mccabe:
  options:
    max-complexity: 10

pep8:
  options:
    max-line-length: 79
    single-line-if-stmt: n

pyroma:
  disable:
    - PYR19
    - PYR16

pep257:
  disable:
    - D000